<?php

declare(strict_types=1);

namespace Codeception\Lib\Connector\Laravel6;

use Exception;
use Illuminate\Contracts\Debug\ExceptionHandler as ExceptionHandlerContract;
use Illuminate\Http\Request;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\HttpFoundation\Response;
use function strpos;

class ExceptionHandlerDecorator implements ExceptionHandlerContract
{
    /**
     * @var ExceptionHandlerContract
     */
    private $laravelExceptionHandler;

    /**
     * @var bool
     */
    private $exceptionHandlingDisabled = true;

    public function __construct(object $laravelExceptionHandler)
    {
        $this->laravelExceptionHandler = $laravelExceptionHandler;
    }

    public function exceptionHandlingDisabled(bool $exceptionHandlingDisabled): void
    {
        $this->exceptionHandlingDisabled = $exceptionHandlingDisabled;
    }

    /**
     * Report or log an exception.
     *
     * @param Exception $e
     * @throws Exception
     */
    public function report(Exception $e): void
    {
        $this->laravelExceptionHandler->report($e);
    }

    /**
     * Determine if the exception should be reported.
     *
     * @param Exception $e
     * @return bool
     */
    public function shouldReport(Exception $e): bool
    {
        return $this->exceptionHandlingDisabled;
    }

    /**
     * Render an exception into an HTTP response.
     *
     * @param Request $request
     * @param Exception $e
     * @return Response
     * @throws Exception
     */
    public function render($request, Exception $e): Response
    {
        $response = $this->laravelExceptionHandler->render($request, $e);

        if ($this->exceptionHandlingDisabled && $this->isSymfonyExceptionHandlerOutput($response->getContent())) {
            // If content was generated by the \Symfony\Component\Debug\ExceptionHandler class
            // the Laravel application could not handle the exception,
            // so re-throw this exception if the Codeception user disabled Laravel exception handling.
            throw $e;
        }

        return $response;
    }

    /**
     * Check if the response content is HTML output of the Symfony exception handler class.
     *
     * @param string $content
     * @return bool
     */
    private function isSymfonyExceptionHandlerOutput(string $content): bool
    {
        return strpos($content, '<div id="sf-resetcontent" class="sf-reset">') !== false ||
            strpos($content, '<div class="exception-summary">') !== false;
    }

    /**
     * Render an exception to the console.
     *
     * @param OutputInterface $output
     * @param Exception $e
     */
    public function renderForConsole($output, Exception $e): void
    {
        $this->laravelExceptionHandler->renderForConsole($output, $e);
    }

    /**
     * @param string|callable $method
     * @param array $args
     * @return mixed
     */
    public function __call($method, array $args)
    {
        return call_user_func_array([$this->laravelExceptionHandler, $method], $args);
    }
}
